# Cấu hình lớp bản đồ: legend, gradient, trường dữ liệu panel
LAYER_CONFIG = {
    'temp_new': {
        'label': 'Nhiệt độ',
        'label_en': 'Temperature',
        'icon': 'thermostat',
        'unit': '°C',
        'gradient': 'linear-gradient(to right, #312783, #1976d2, #00bcd4, #4caf50, #ffeb3b, #ff9800, #f44336)',
        'legend_min': '-40°C',
        'legend_max': '50°C',
        'field': 'temp',
    },
    'pressure_new': {
        'label': 'Áp suất',
        'label_en': 'Pressure',
        'icon': 'speed',
        'unit': 'hPa',
        'gradient': 'linear-gradient(to right, #0d1b4d, #1565c0, #26c6da, #66bb6a, #ffee58, #ff7043, #c62828)',
        'legend_min': '950 hPa',
        'legend_max': '1050 hPa',
        'field': 'pressure',
    },
    'wind_new': {
        'label': 'Tốc độ gió',
        'label_en': 'Wind speed',
        'icon': 'air',
        'unit': 'm/s',
        'gradient': 'linear-gradient(to right, #37474f, #546e7a, #29b6f6, #66bb6a, #ffee58, #ff9800, #e53935)',
        'legend_min': '0 m/s',
        'legend_max': '100 m/s',
        'field': 'wind_speed',
    },
    'precipitation_new': {
        'label': 'Lượng mưa',
        'label_en': 'Precipitation',
        'icon': 'grain',
        'unit': 'mm',
        'gradient': 'linear-gradient(to right, #e1f5fe, #4fc3f7, #81c784, #fff176, #ffb74d, #e57373, #7b1fa2)',
        'legend_min': '0 mm',
        'legend_max': '10 mm',
        'field': 'rain',
    },
    'clouds_new': {
        'label': 'Mây',
        'label_en': 'Clouds',
        'icon': 'cloud',
        'unit': '%',
        'gradient': 'linear-gradient(to right, #263238, #607d8b, #b0bec5, #eceff1, #81d4fa, #42a5f5, #5e35b1)',
        'legend_min': '0%',
        'legend_max': '100%',
        'field': 'clouds',
    },
}
